services:
  # NestJS API for production
  api-prod:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}-api-prod
    build:
      context: ../../..
      dockerfile: ./docker/builder/api/Dockerfile.api.prod
      args:
        - API_PORT=${API_PORT}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      # Runtime
      - NODE_ENV=production
      - LOG_LEVEL=warn
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # API Configuration
      - API_PORT=${API_PORT}
      
      # URLs
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - API_URL=http://${COMPOSE_PROJECT_NAME:-nextjs-nestjs}-api-prod:${API_PORT}
      
      # Authentication
      - AUTH_SECRET=${AUTH_SECRET}
      - DEV_AUTH_KEY=${DEV_AUTH_KEY}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${API_PORT}/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 5
    networks:
      - app_network_prod
    volumes:
      - bun_cache_prod:/root/.bun/install/cache
      - turbo_cache_prod:/root/.cache/turbo

networks:
  app_network_prod:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_app_network_prod
    driver: bridge

volumes:
  bun_cache_prod:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_bun_cache_prod
  turbo_cache_prod:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-nestjs}_turbo_cache_prod
